# Generated by Django 5.1.7 on 2025-07-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationdemo', '0002_expensecategory_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('isbn', models.CharField(max_length=13)),
                ('authors', models.ManyToManyField(to='relationdemo.author')),
            ],
        ),
    ]
